name: sbb-robust-planer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - ipywidgets
  - voila
  - numpy
  - pandas
  - pip
  - pip:
    - networkx
    - geopy
    - matplotlib
    - pyarrow
    - ipymaterialui
